import {
  BookOpen,
  Calendar,
  CheckSquare,
  ClipboardList,
  FileText,
  GraduationCap,
  LayoutDashboard,
  Library,
  PenTool,
  School,
  Users,
} from 'lucide-react';

export const navConfig = {
  admin: [
    { label: 'Dashboard', path: '/', icon: LayoutDashboard },
    { label: 'Teachers', path: '/teachers', icon: Users },
    { label: 'Classes', path: '/classes', icon: School },
    { label: 'Students', path: '/students', icon: GraduationCap },
    { label: 'Core Subjects', path: '/core-subjects', icon: Library },
    { label: 'Subjects', path: '/subjects', icon: BookOpen },
    { label: 'Attendance', path: '/attendance', icon: ClipboardList },
    { label: 'Syllabus', path: '/syllabus', icon: CheckSquare },
    { label: 'Tests & Results', path: '/tests', icon: PenTool },
    { label: 'Notices', path: '/notices', icon: FileText },
    { label: 'Events', path: '/events', icon: Calendar },
  ],
  teacher: [
    { label: 'Dashboard', path: '/', icon: LayoutDashboard },
    { label: 'My Classes', path: '/classes', icon: School },
    { label: 'Students', path: '/students', icon: GraduationCap },
    { label: 'Subjects', path: '/subjects', icon: BookOpen },
    { label: 'Attendance', path: '/attendance', icon: ClipboardList },
    { label: 'Syllabus', path: '/syllabus', icon: CheckSquare },
    { label: 'Tests & Results', path: '/tests', icon: PenTool },
    { label: 'Notices', path: '/notices', icon: FileText },
    { label: 'Events', path: '/events', icon: Calendar },
  ],
  student: [
    { label: 'Dashboard', path: '/', icon: LayoutDashboard },
    { label: 'My Profile', path: '/students/me', icon: GraduationCap },
    { label: 'Attendance', path: '/attendance', icon: ClipboardList },
    { label: 'Syllabus', path: '/syllabus', icon: CheckSquare },
    { label: 'Tests & Results', path: '/tests', icon: PenTool },
    { label: 'Notices', path: '/notices', icon: FileText },
    { label: 'Events', path: '/events', icon: Calendar },
  ],
};
