import {
  BookOpen,
  Calendar,
  CheckSquare,
  ClipboardList,
  FileText,
  GraduationCap,
  LayoutDashboard,
  Library,
  PenTool,
  School,
  Users,
} from 'lucide-react';

export const navConfig = {
  admin: [
    { label: 'Dashboard', path: '/', icon: LayoutDashboard },
    { label: 'Teachers', path: '/teachers', icon: Users },
    { label: 'Classes', path: '/classes', icon: School },
    { label: 'Students', path: '/students', icon: GraduationCap },
    { label: 'Core Subjects', path: '/core-subjects', icon: Library },
    { label: 'Subjects', path: '/subjects', icon: BookOpen },
    { label: 'Attendance', path: '/attendance', icon: ClipboardList },
    { label: 'Syllabus', path: '/syllabus', icon: CheckSquare },
    { label: 'Tests & Results', path: '/tests', icon: PenTool },
    { label: 'Notices', path: '/notices', icon: FileText },
    { label: 'Events', path: '/events', icon: Calendar },
  ],
  teacher: [
    { label: 'Dashboard', path: '/', icon: LayoutDashboard },
    { type: 'divider', label: 'My Assignments' },
    { label: 'My Classes', path: '/classes', search: '?scope=my', icon: School },
    { label: 'My Students', path: '/students', search: '?scope=my', icon: GraduationCap },
    { label: 'My Subjects', path: '/subjects', search: '?scope=my', icon: BookOpen },
    { type: 'divider', label: 'School' },
    { label: 'All Classes', path: '/classes', icon: School },
    { label: 'All Students', path: '/students', icon: GraduationCap },
    { label: 'All Subjects', path: '/subjects', icon: BookOpen },
    { label: 'Teachers', path: '/teachers', icon: Users },
    { type: 'divider', label: 'Tools' },
    { label: 'Attendance', path: '/attendance', icon: ClipboardList },
    { label: 'Syllabus', path: '/syllabus', icon: CheckSquare },
    { label: 'Tests & Results', path: '/tests', icon: PenTool },
    { label: 'Notices', path: '/notices', icon: FileText },
    { label: 'Events', path: '/events', icon: Calendar },
  ],
  student: [
    { label: 'Dashboard', path: '/', icon: LayoutDashboard },
    { label: 'My Profile', path: '/students/me', icon: GraduationCap },
    { label: 'Attendance', path: '/attendance', icon: ClipboardList },
    { label: 'Syllabus', path: '/syllabus', icon: CheckSquare },
    { label: 'Tests & Results', path: '/tests', icon: PenTool },
    { label: 'Notices', path: '/notices', icon: FileText },
    { label: 'Events', path: '/events', icon: Calendar },
  ],
};
